/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientIf.java
 *
 * Created on 2010-5-14, 16:15:44
 */

package client;

import javax.swing.JOptionPane;

/**
 *
 * @author fanzhidong
 */
public class ClientIf extends javax.swing.JFrame {

    public static ClientIf instance =null;
    Client client =new Client();
    /** Creates new form ClientIf */
    public ClientIf() {
        super("Client");
        instance=this;
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        txtIp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCnt = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        sltProt = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSend = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtIp.setText("172.19.44.100");

        jLabel1.setText("ServerIP:");

        btnCnt.setText("Connect");
        btnCnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCntActionPerformed(evt);
            }
        });

        btnSend.setText("Send");
        btnSend.setEnabled(false);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        sltProt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TCP", "UDP" }));
        sltProt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sltProtActionPerformed(evt);
            }
        });

        jLabel2.setText("Protocol：");

        txtSend.setColumns(20);
        txtSend.setFont(txtSend.getFont().deriveFont((txtSend.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 14));
        txtSend.setLineWrap(true);
        txtSend.setRows(5);
        txtSend.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtSend);

        txtChat.setColumns(20);
        txtChat.setEditable(false);
        txtChat.setFont(txtChat.getFont().deriveFont((txtChat.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 14));
        txtChat.setLineWrap(true);
        txtChat.setRows(5);
        txtChat.setWrapStyleWord(true);
        txtChat.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(txtChat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(txtIp, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCnt))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sltProt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addComponent(btnSend)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnCnt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(jLabel2)
                    .addComponent(sltProt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCntActionPerformed
        // TODO add your handling code here:
        this.getTxtIp().setEnabled(false);
        this.btnCnt.setEnabled(false);        
        this.sltProt.setEnabled(false);
        String ip=this.getTxtIp().getText();

        if(client.connect(ip))
        {
            this.getBtnSend().setEnabled(true);
        }
    }//GEN-LAST:event_btnCntActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        String txt =this.getTxtSend().getText();
        if(!txt.isEmpty())
            client.send(txt);
        else
            JOptionPane.showMessageDialog(null, "Text sending should not be empty !");
    }//GEN-LAST:event_btnSendActionPerformed

    private void sltProtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sltProtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sltProtActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientIf().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCnt;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox sltProt;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextArea txtSend;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the txtSend
     */
    public javax.swing.JTextArea getTxtChat() {
        return txtChat;
    }

    /**
     * @return the sltProt
     */
    public javax.swing.JComboBox getSltProt() {
        return sltProt;
    }

    /**
     * @return the btnSend
     */
    public javax.swing.JButton getBtnSend() {
        return btnSend;
    }

    /**
     * @return the txtSend
     */
    public javax.swing.JTextArea getTxtSend() {
        return txtSend;
    }

    /**
     * @return the txtIp
     */
    public javax.swing.JTextField getTxtIp() {
        return txtIp;
    }

}
