/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ServerIf.java
 *
 * Created on 2010-5-14, 16:12:03
 */

package server;

/**
 *
 * @author fanzhidong
 */
public class ServerIf extends javax.swing.JFrame {

    public static ServerIf instance =null;

    /** Creates new form ServerIf */
    public ServerIf() {
        super("Server");
        instance=this;
        initComponents();
        new Server();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtShow = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtShow.setColumns(20);
        txtShow.setEditable(false);
        txtShow.setFont(txtShow.getFont().deriveFont((txtShow.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 14));
        txtShow.setLineWrap(true);
        txtShow.setRows(5);
        txtShow.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtShow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerIf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtShow;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the txtShow
     */
    public javax.swing.JTextArea getTxtShow() {
        return txtShow;
    }

}
